//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace RaydraTournament
{
 
    /* \enum MovingState
            This enumeration contains the type of locomotion that the player is in at anytime
            such as standing still or walking
    
        */
		public enum MovingState //!Indicate the type of motion that the player currently in
		{

            //! The player is standing still
            IsStandingStill,
            //! The player is walking
            IsWalking,
            //! The player is moving backwards
            IsWalkingBackward,
            //! The player is running
            IsRunning,
            //! The player is passing the ball
            IsPassing,
             //!The player is strafing (dodging
             IsStrafing,
             //! The player is doing a wall flip
             IsWallFliping,
             //! The player is tackling 
             IsTackling,
            //!The Player is in a charged run
             IsChargedRunning,

            
			
		}


    /* \enum AttackMode 
            Indicates if the player is attacking or not
            RaydraState needs to be checked before this mode is checked
        \sa RaydraState
       
    */

    public enum AttackMode
 
    {
        //! The player in not firing his ability
        NotFiringAbility,
        //! The player is firing his ability
        IsFiringAbility

    }

    /* \enum JumpingState
   This determines wether or not the player is jumping or not */
    public enum JumpingState
	{
        /*!Player is not jumping*/
        NotJumping,
        //!The player is jumping
        IsJumping, 
	
	}
  
    /* \enum RaydraState
This determines wether or not the player is jumping or not*/
    public enum RaydraState //!indicates if the player is in RaydraMode or not
    {
        //! Not in Raydra Mode this is the default Raydra Mode
        NotInRaydraMode,
        //! Is in RaydraMode
        IsInRaydraMode

    }


    /* \enum CameraPerspective
        This indicates what the camera is doing and how it is positoined at the moment
*/
    public enum CameraPerspective //How the player is seeing the scene
	{
        //!The camera is not moving
        Normal,
        //! The camera is Rotating
        IsRotating,
        //!This means that the camera has shifed to a passing view
        PassMode
    }


    /* \enum  BallPossessionState

        Indicates if the player has the ball or not
    
        
        */
    public enum BallPossessionState
    {   //!does not have the ball
        DoseNotHaveBall,
        //! has the ball
        HasBall, 

	}


    /* \enum VerticalVelocityState 
        Indicates the player is going up down or state on even ground

        */
    public enum BallThrowingState
	{
        //! Not thorwing the ball
        NotBeingThrown,
        //! thorwing the ball
        IsBeingThrown,

    }


    /* \enum PhaseState

        Indicates if the player is phase attacking or not

    */
    public enum PhaseState
    {
        //!default State: The player is not phasing
        IsNotPhasing,
        //!The Player is phasing
        IsPhasing, 

    }

    /* \enum TackleState

    Indicates if the player is tackling or not

    */
    public enum TackleState
    {
        //!default tackle state*/
        IsNotTackling,
        //!Player is in the tackling action*/ 
        IsTackling,  

    }

    /* \enum PhaseHitState

     Indicates what type of contact the player has made with another player
     */
    public enum PhaseHitState
    {
        //!There has been no physical contact made weither phased attacked or being phased attacked*/
        NoContact,
        //!State when the player is Hit by the phase*/
        HasBeenHit,
        //!State when the player has tackled another phase*/
        HasHitOpponent
    }

    /* \enum TackleHitState

        Indicates what type of contact the player has made with another player
        
        There can be No contact , tackled the other player or was tackled by another player
   
        */
    public enum TackeHitState
    {
        //!State when the player is Hit by the tackle*/
        NoContact,     
        //!State when the player has tackled another player*/ HasBeenHit, 
        HasHitOpponent


    }

}

