//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

using System.Collections;


namespace RaydraTournament
{


		public class RaydraPlayer:MonoBehaviour
		{ 

		

			public RaydraPlayer ( )
				{
		
		        //!the player info that unity will keep tract of
			p_fCameraAngleTheta = 43f; //!initialize the angle that player if facing
			p_fCameraAnglePhi = 45f; //!The camera is initially in this state
            p_fPlayerToFocusAngleTheta = 43f; //!initialize the angle that player if facing
            p_fPlayerToFocusAnglePhi = 45f; //!//!initialize the angle that player if facing in the upward direction
            p_fJumpVelocity = .40f; //!initialize the upward jump force
			ForceOfGravity = 1f / 60f; //!this will have a unit per second force of gravity, in the downward direction 
			p_fOrientationAngle = 90f; //!Angle that the player is facing in degrees
			p_v3OrientationVect = new Vector3 (0, 0, 1f); //!Direction player is facing represented as an angle
            p_v3PlayerToFocusVect = new Vector3(0, 0, 0); //!The vector the represents the direction the camera if facing
            p_v3PlayerToCameraVect = new Vector3(0, 0, 0);//!The Vector Data the represent the player to camera direction
            PlayerMovementState = MovingState.IsStandingStill; //!Intially the player is not moving
			p_ePlayerJumpState = JumpingState.NotJumping; //!initlialize the the player is not jumping
            PlayerTackleHitState = TackeHitState.NoContact; //!Initial the tackle state of the player
            PlayerTackleState = TackleState.IsNotTackling; //!Initial the tackle state of the player
            PlayerAttackState = AttackMode.NotFiringAbility; //!Initial the shoot state of the player
            PlayerRaydraState = RaydraState.NotInRaydraMode; //!initailly the player is not in Raydra Mode
			PlayerCameraState = CameraPerspective.Normal; //!initially the camera to do nothing
            PlayerPhaseState = PhaseState.IsNotPhasing;
            //VerticalMovementState = VerticalVelocityState.NotMoving;  //!Initial the vertical state of the player
                                                                      //	PlayerMotionVector = new Vector3 (this.transform.position.x,.transform.position.y,playerData.transform.position.z);
            p_v3PlayerVectorDirection = Vector3.zero; //!* This is direction that te player is headed as a vector
            p_rfwArmWeapon = null; //!reference to the arm weapon on the player which is null to begin with
            p_bFacePlayer = false; //! variable that determine weather or not to face the player, this variable determine weather or not this medthod is recursive
            p_fMass = 0f; //!initialize the mass of the player
            p_StateTime = 0f;// Time elasped in current state
            p_Collider = null;
            
        }




		public GameObject Player; //!this is the player data that unity manipulates
		public	MovingState PlayerMovementState ; //!The current action that the player is taking at the moment
		public	RaydraState PlayerRaydraState; //! Indicates wether or not the player is in Raydra mode or not
		public AttackMode PlayerAttackState; //! Determines wether the player is firing or not
		public JumpingState p_ePlayerJumpState;//! The current jumping state of the player
		public CameraPerspective  PlayerCameraState; //! what the camera is doing at the moment
		//public VerticalVelocityState VerticalMovementState;//! the vertical motion of the player 
		public TackleState PlayerTackleState; //! indicates wether the player is tackling or not
        public TackeHitState PlayerTackleHitState; //! indicates what type of contact has been made
        public PhaseState PlayerPhaseState; //! indicates wether the player is tackling or not
        public PhaseHitState PlayerPhaseHitState; //! indicates what type of contact has been made
        public X8Timer EventTimer = new X8Timer(7f); //! this timer class will time the duration of certain actions
        private Vector3 AccumForce; //! the force that is acculated on the player --this quantity is a sum a mulitple forece


		//	private Vector3 CurrentPosition; //the position of the player
	
		public Vector3 PlayerDirection = new Vector3(0,0,0);  //! the direction that the player is facton
		 // the angle that player is facing
		public Mesh PlayerModel; // The actual model the player is using, will chnage based Raydra state
		public float Jumptime=0; //the time that player is in the air
		public float ForceOfGravity=0; //force of gracity in the vertical direction
		public float TackleForce = 3; // this is Tackle force that is exerted on the player when he gets hit


		//this is angle direction that the player is facing. Player Movement is relative
		public float p_fOrientationAngle {
						set;
						get;
		}

		public Vector3 p_v3OrientationVect {
			set;
			get;

		}

		public float p_fDestinationAngle {
			set;
			get;

		}

		//this is the direction that the player is moving in
		public Vector3 p_v3PlayerMotionVector {
			set;
			get;
		}
        //this the horizontal angle of the camera relative to the focas point
		public float p_fCameraAngleTheta {
				set;
				get;
		}

        //this is the vertical angle of the camera relative to the ground
		public float p_fCameraAnglePhi {
			set;
			get;
		}
       public float p_fPlayerToFocusAngleTheta  //!initialize the angle that player if facing
        {
            get;
            set;

        }
        public float p_fPlayerToFocusAnglePhi
        {
            get;
            set;
        }

        //this the accerlation of the vertical velocity when the player is jumping
		public float p_fJumpVelocity {
						get;
						set;

		}
	
        //this the direction the player is going at the moment
        public Vector3 p_v3PlayerVectorDirection
        {
            get;
            set;
        }


       public Vector3 p_v3PlayerToCameraVect
        {
            get;
            set;

        } 


        //this the vector that goes from the camera to the player
        public Vector3 p_v3PlayerToFocusVect
        {
            get;
            set;

        }

		public void addForce( Vector3  force){//adds a force to the accumlated force this frame

			AccumForce+=force;	
			}


		public void clearForces(){//clears the forces that have added up in the player for this frame 

			AccumForce = Vector3.zero;

		}

        

        public RaydraWeapon p_rfwArmWeapon
        {
            get;
            set;

        }

        public Rigidbody p_rbRaydraBody
        {
            get;
            set;

        }

        public bool p_bFacePlayer
        {
            get;
            set;

        }

        public float p_fMass
        {
            get;
            set;
        }

        public float p_StateTime
        {
            get;
            set;
        }

        public Collider p_Collider
        {
            get;
            set;
        }


}//end of class


}//end of name space

